{% set name = "pyopengl-accelerate" %}
{% set version = "3.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyOpenGL-accelerate/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 85957c7c76975818ff759ec9243f9dc7091ef6f373ea37a2eb50c320fd9a86f3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.28
    - numpy {{ numpy }}
    - setuptools >=42.0
    - wheel
  run:
    - python
    - numpy
    - pyopengl
    - freeglut  # [not osx]

test:
  source_files:
    - tests
  imports:
    - OpenGL_accelerate
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://mcfletch.github.io/pyopengl
  license: LicenseRef-pyopengl
  license_file: license.txt
  license_family: BSD
  summary: Acceleration code for PyOpenGL
  description: |
    This set of C (Cython) extensions provides acceleration of common operations for slow points in PyOpenGL .
  doc_url: https://mcfletch.github.io/pyopengl/documentation/index.html
  dev_url: https://github.com/mcfletch/pyopengl/tree/master/accelerate

extra:
  recipe-maintainers:
    - jjhelmus
