{% set name = "pyopengl-accelerate" %}
{% set version = "3.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/P/PyOpenGL-accelerate/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 82751c83f0a6f732b8b5923990edc2441d38176a98756b1718e8d6c4379f5a71

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.28
    - numpy {{ numpy }}
    - freeglut {{ freeglut }}  # [not osx]
    - setuptools >=42.0
    - numpy
  run:
    - python
    - numpy
    - pyopengl {{ version }}
    - freeglut  # [not osx]
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  imports:
    - OpenGL_accelerate
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://mcfletch.github.io/pyopengl
  license: LicenseRef-pyopengl
  license_file: license.txt
  license_family: BSD
  summary: Acceleration code for PyOpenGL
  description: |
    This set of C (Cython) extensions provides acceleration of common operations for slow points in PyOpenGL .
  doc_url: https://mcfletch.github.io/pyopengl/documentation/index.html
  dev_url: https://github.com/mcfletch/pyopengl/tree/master/accelerate

extra:
  recipe-maintainers:
    - jjhelmus
